###
GET http://localhost:3000/todos/

###
GET http://localhost:3000/todos/?priority=LOW

###
GET http://localhost:3000/todos/?status=DONE 

###
GET http://localhost:3000/todos/?priority=LOW&status=TO%20DO

###
GET http://localhost:3000/todos/1/

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id":5,
    "todo":"LEARN React",
    "priority":"HIGH",
    "status":"IN PROGRESS"
}

###

put http://localhost:3000/todos/1/
Content-Type: application/json

{
       "priority":"HIGH"
}

###

DELETE http://localhost:3000/todos/5/
